"""Markdown report generation."""

from __future__ import annotations

import re
from datetime import UTC, datetime

from pipeline_agent.github_client import WorkflowContext
from pipeline_agent.openrouter_client import LLMResponse


def build_context_for_llm(
    ctx: WorkflowContext,
    historical_failures: list[dict] | None = None,
) -> str:
    sections = [
        f"# Pipeline Failure Context",
        "",
        f"- **Workflow**: {ctx.workflow_name} (`{ctx.workflow_path}`)",
        f"- **Run ID**: {ctx.run_id} (attempt {ctx.run_attempt})",
        f"- **Branch**: {ctx.head_branch}",
        f"- **Commit**: `{ctx.head_sha[:8]}` — {ctx.head_commit_message}",
        f"- **Triggered by**: {ctx.actor}",
        f"- **Event**: {ctx.event}",
        f"- **URL**: {ctx.html_url}",
        "",
    ]

    if ctx.failed_jobs:
        sections.append("## Failed Jobs")
        for job in ctx.failed_jobs:
            sections.append(f"- **{job.job_name}** → step `{job.step_name}`")
            sections.append("  ```")
            sections.append(job.log_excerpt[:3000])
            sections.append("  ```")
        sections.append("")

    if ctx.logs_summary:
        sections.append("## Workflow Logs Summary")
        sections.append(ctx.logs_summary[:20000])
        sections.append("")

    sections.append("## Full Logs (truncated if large)")
    sections.append("```")
    sections.append(ctx.log_text[:40000])
    sections.append("```")
    sections.append("")

    if ctx.recent_commits:
        sections.append("## Recent Commits")
        if ctx.commits_summary:
            sections.append(ctx.commits_summary[:8000])
        else:
            for c in ctx.recent_commits:
                files = ", ".join(c.get("files_changed", [])[:5])
                extra = ""
                if len(c.get("files_changed", [])) > 5:
                    extra = f" (+{len(c['files_changed']) - 5} more files)"
                sections.append(
                    f"- `{c['sha']}` by {c['author']}: {c['message']}"
                    + (f"\n  Files: {files}{extra}" if files else "")
                )
        sections.append("")

    if ctx.similar_issues:
        sections.append("## Similar GitHub Issues")
        if ctx.issues_summary:
            sections.append(ctx.issues_summary[:6000])
        else:
            for issue in ctx.similar_issues:
                line = f"- #{issue['number']} [{issue['state']}] {issue['title']} — {issue['url']}"
                if issue.get("solution_hint"):
                    line += f"\n  Hint: {issue['solution_hint']}"
                sections.append(line)
        sections.append("")

    if historical_failures:
        sections.append("## Historical Failures (Postgres)")
        for h in historical_failures:
            sections.append(
                f"- Run #{h.get('workflow_run_id')} ({h.get('investigated_at')}): "
                f"{(h.get('root_cause') or 'unknown')[:200]}"
            )
        sections.append("")

    return "\n".join(sections)


def build_failure_report(
    ctx: WorkflowContext,
    llm_response: LLMResponse,
    *,
    secrets_redacted: bool = False,
) -> str:
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    header = [
        f"# Pipeline Failure Report — {ctx.workflow_name}",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Run | [#{ctx.run_id}]({ctx.html_url}) |",
        f"| Branch | `{ctx.head_branch}` |",
        f"| Commit | `{ctx.head_sha[:8]}` |",
        f"| Actor | {ctx.actor} |",
        f"| Generated | {timestamp} |",
        f"| Model | {llm_response.model} |",
        "",
    ]

    if secrets_redacted:
        header.append("> ⚠️ Secrets were detected and redacted from this report.")
        header.append("")

    body = [
        "---",
        "",
        llm_response.content,
        "",
        "---",
        "",
        "## Investigation Metadata",
        f"- Prompt tokens: {llm_response.prompt_tokens}",
        f"- Completion tokens: {llm_response.completion_tokens}",
        f"- Total tokens: {llm_response.total_tokens}",
        "",
        "*Generated by [Pipeline Health Monitor](https://github.com/actions)*",
    ]

    return "\n".join(header + body)


def build_success_summary(ctx: WorkflowContext, summary: str | None = None) -> str:
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Pipeline Success — {ctx.workflow_name}",
        "",
        f"- **Run**: [#{ctx.run_id}]({ctx.html_url})",
        f"- **Branch**: `{ctx.head_branch}`",
        f"- **Commit**: `{ctx.head_sha[:8]}`",
        f"- **Actor**: {ctx.actor}",
        f"- **Time**: {timestamp}",
        "",
    ]
    if summary:
        lines.extend(["## Summary", "", summary, ""])
    return "\n".join(lines)


def extract_root_cause(llm_content: str) -> str:
    """Extract root cause from LLM output for Postgres indexing."""
    # New format: **Root Cause**: summary
    bold_match = re.search(r"\*\*Root Cause\*\*:\s*(.+)", llm_content, re.IGNORECASE)
    if bold_match:
        return bold_match.group(1).strip()[:500]

    # Legacy markdown heading format
    lines = llm_content.splitlines()
    in_section = False
    root_lines: list[str] = []
    for line in lines:
        if line.strip().lower().startswith("## root cause"):
            in_section = True
            continue
        if in_section and line.strip().startswith("## "):
            break
        if in_section and line.strip():
            root_lines.append(line.strip())
    if root_lines:
        return " ".join(root_lines)[:500]
    return llm_content[:500]


def extract_risk_level(llm_content: str) -> str:
    """Extract risk level from LLM output (**Risk Level**: Low | Medium | High)."""
    match = re.search(
        r"\*\*Risk Level\*\*:\s*\[?(Low|Medium|High)\]?",
        llm_content,
        re.IGNORECASE,
    )
    if match:
        return match.group(1).capitalize()
    return "Unknown"


def build_investigation_result(
    *,
    success: bool,
    workflow_run_id: str | int,
    analysis: str = "",
    root_cause: str = "",
    risk_level: str = "Unknown",
    error: str | None = None,
    issue_number: int | None = None,
) -> dict:
    """Build the structured investigation response dict (§8 contract)."""
    return {
        "success": success,
        "workflow_run_id": str(workflow_run_id),
        "analysis": analysis,
        "root_cause": root_cause,
        "risk_level": risk_level,
        "error": error,
        "issue_number": issue_number,
    }


def build_success_result(
    *,
    success: bool,
    workflow_run_id: str | int,
    analysis: str = "",
    email_sent: bool = False,
    error: str | None = None,
) -> dict:
    """Build structured JSON for a successful workflow run (lightweight, no LLM)."""
    return {
        "success": success,
        "workflow_run_id": str(workflow_run_id),
        "status": "success",
        "analysis": analysis,
        "email_sent": email_sent,
        "error": error,
    }

